In [3]:
import pandas as pd

df = pd.read_parquet(r"C:\Users\lola\github\p04_golez_jackwerth_2024\_data\crsp_treasury_returns.parquet")
df_fred_treasury_rates= pd.read_parquet(r"C:\Users\lola\github\p04_golez_jackwerth_2024\_data\fred_treasury_rates.parquet")
print("Loaded successfully!")

Loaded successfully!

In [4]:
df.describe()

                                date  treasury_2y_ret  treasury_10y_ret
count                           1189      1008.000000       1004.000000
mean   1975-06-30 14:55:00.252312864         0.003735          0.004121
min              1925-12-31 00:00:00        -0.036947         -0.066819
25%              1950-09-29 00:00:00         0.000179         -0.006174
50%              1975-06-30 00:00:00         0.002319          0.002488
75%              2000-03-31 00:00:00         0.006766          0.013715
max              2024-12-31 00:00:00         0.084198          0.099993
std                              NaN         0.007426          0.020054

In [5]:
df_fred_treasury_rates.describe()

                                date        rf_1m   treasury_2y  treasury_10y
count                          16436  5857.000000  12143.000000  15735.000000
mean   1993-07-02 02:24:02.102701440     0.015525      0.049908      0.058445
min              1962-01-02 00:00:00     0.000000      0.000900      0.005200
25%              1977-10-02 06:00:00     0.000700      0.016300      0.038600
50%              1993-07-01 12:00:00     0.009300      0.047300      0.055400
75%              2009-04-01 06:00:00     0.023700      0.072000      0.075800
max              2024-12-31 00:00:00     0.060200      0.169500      0.158400
std                              NaN     0.017899      0.037098      0.029580